################################################################################
.PHONY: all
all: install

################################################################################
.PHONY: install
install:
	mkdir -p ~/.config/rofi
	cp -f main.rasi ~/.config/rofi
	cp -f powermenu.rasi ~/.config/rofi

################################################################################
.PHONY: clean
clean:
	rm -rf *~
