################################################################################
.PHONY: all
all: install

################################################################################
.PHONY: install
install:
	mkdir -p ~/.config/polybar
	cp -f config.ini ~/.config/polybar
	cp -f launch.sh ~/.config/polybar

################################################################################
.PHONY: clean
clean:
	rm -rf *~
