.PHONY: all install

all: install

install:
	cp -rf .bash_aliases ~/.bash_aliases
	cp -rf .bash_export ~/.bash_export
	cp -rf .bashrc ~/.bashrc
	cp -rf .english.txt ~/.english.txt
	cp -rf .sholde ~/.sholde
	cp -rf .makefile.template ~/.makefile.template

clean:
	rm -Rf *~ .*~
