################################################################################
.PHONY: all
all: install

################################################################################
.PHONY: install
install:
	cp -f .bash_aliases ~/.bash_aliases
	cp -f .bash_export ~/.bash_export
	cp -f .bashrc ~/.bashrc
	cp -f .sholde ~/.sholde

################################################################################
.PHONY: clean
clean:
	rm -rf *~ .*~
